### ISSUE TITLE
Strona my activity

### ISSUE THREAD

**Issue by rocketfingers** [rocketfingers/YourKpi#1]
![Show my activity](https://user-images.githubusercontent.com/7503952/106768572-52505780-663c-11eb-936d-220a22b33f3c.png)

**Comment by PKacprow** [comment]
??

**Comment by 4YourCompany** [comment]
chciałbym aby był taki raport według nazwiska i imienia

![obraz](https://user-images.githubusercontent.com/77233863/107127953-16c2c100-68ba-11eb-8a16-5c254ab86989.png)
