### ISSUE TITLE
Oferta - brak cen produktów

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#11]
W Oferta - brak jest cen produktów , nie podciągają się.
Czy można zrobić tak, żeby była to cena jednostokowa z Produkty x ilość produktów?

![obraz](https://user-images.githubusercontent.com/77233863/107120576-af434c00-688e-11eb-8d3b-ed8d78e1ad98.png)

**Comment by PKacprow** [comment]
Odnośnie ceny jednostkowej - cena produkcu*ilosc,
Natomiast co z ceną sprzedaży? Zostaje pusta? Czy ma być wstawiona domyślnie taka, jak jednostkowa?

**Comment by PKacprow** [comment]
Ustaliliśmy, że w obu polach wyswietla sie cena jesdnostkowa
