### ISSUE TITLE
Historia Aktywności - błąd - nie pokazuje logowań na właściwych Klientach

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#18]
Historia aktywności jest zrobiona super!

Zobacz proszę tylko dlaczego nie pokazuje logowań z danego dnia tych właściwych. Użytkownik Andrzej Binias jest zalogowany na poniższej aktywności 

![image](https://user-images.githubusercontent.com/77233863/108200618-fe0aa480-711e-11eb-8a46-7299c381ddf2.png)

a w historii logowań widać 

![image](https://user-images.githubusercontent.com/77233863/108200715-2397ae00-711f-11eb-9fe1-de7c946797b1.png)

**Comment by rocketfingers** [comment]
Poprawiono na widoku ISNULL(pcs.CzasStop, GETDATE()) AS CzasStop,
