### ISSUE TITLE
Aktywności - rozpoczęcie logowania czasu - Części

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#19]
Czy można zrobić tak , żeby okienko z Częściami pojawiało przy rozpoczęciu logowania czasu?

![image](https://user-images.githubusercontent.com/77233863/108201339-fdbed900-711f-11eb-8ebc-745f2685b655.png)

**Comment by rocketfingers** [comment]
Uzgodnione, ze zostanie tak jak jest
