### ISSUE TITLE
Produkt - brak możliwości dodania nowego prouktu

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#20]
poniżej przykład,

nie mogę zatwierdzić nowego produktu .Po kliknięciu na zatwierdź nie zapisuje.

![image](https://user-images.githubusercontent.com/77233863/108205803-d5d27400-7125-11eb-9561-46b6d83785ea.png)

**Comment by PKacprow** [comment]
hmm... ja bez problemu dodałem produkt 'test123'. Przydałyby się dane dla których nie działa....

**Comment by 4YourCompany** [comment]
spróbuj wpisać 

ZK-K_080_016_II_020_120

**Comment by PKacprow** [comment]
no i się dodał.... ;/

**Comment by 4YourCompany** [comment]
znowu nie mogę dodać klikam i nic się nie dzieje ...

![obraz](https://user-images.githubusercontent.com/77233863/108630353-9dec6900-7464-11eb-96b2-537c87685209.png)
