### ISSUE TITLE
Klienci - brak możliwości wpisania nowego Klienta 

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#22]
tak jak rozmawialiśmy po wpisaniu dla nowego Klienta NIP z kreskami pojawia się nastepujący komunikat.
Nie możnadopisać nowego Klienta.

\
![image](https://user-images.githubusercontent.com/77233863/108218657-2e5d3d80-7135-11eb-928b-4a887b09e7f4.png)

**Comment by PKacprow** [comment]
ok,  chyba jest wymagana okreslona dlugosc dla NIP - 10 znakow
