### ISSUE TITLE
Oferta - nie można dopisać 

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#23]
Po wpisaniu nowej oferty wyskoczył błąd, poniżej opis

![obraz](https://user-images.githubusercontent.com/77233863/108269806-d2170f80-716e-11eb-9f0d-5313cfe38e73.png)

**Comment by 4YourCompany** [comment]
tu jest zrzut przed błedem

![Uploading image.png…]()

**Comment by PKacprow** [comment]
hmm ten zrzut nie działa ...

**Comment by 4YourCompany** [comment]
juz umiesciłem dwa nowe

**Comment by 4YourCompany** [comment]
To jest zrzut w momencie pisania oferty

![obraz](https://user-images.githubusercontent.com/77233863/108533121-eaa33900-72d8-11eb-98c5-4b901b807329.png)

**Comment by 4YourCompany** [comment]
a to jest zrzut z błedem

![obraz](https://user-images.githubusercontent.com/77233863/108533239-0c042500-72d9-11eb-8a0c-9f6ba8456ccd.png)

**Comment by 4YourCompany** [comment]
![obraz](https://user-images.githubusercontent.com/77233863/108533290-1a524100-72d9-11eb-954f-0efb66288b5d.png)

**Comment by 4YourCompany** [comment]
Zrobiłem Ctrl+R i Ctrl Shift +R

I dalej wyskakuje ten sam błąd

Po wpisaniu kilku procesów na poziomie oferty, oraz kilku z poziomie produktu pojawił się nowy



![obraz](https://user-images.githubusercontent.com/77233863/108621455-f60a7780-7432-11eb-89ff-ff8ee997ce6b.png)
