### ISSUE TITLE
Aktywności - zamykanie stepu Części

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#26]
Przy zamykaniu stepu , części powinny "podbierać" się tylko z danej listy części Produktów .
W tym przypadku mamy zawór ZK-KD 020 a części widać 65 (chyba podbierają) się wszystkie.

Dla takich produktów które nie mają listy części proszę aby lista była pusta.

![obraz](https://user-images.githubusercontent.com/77233863/108522401-13253600-72cd-11eb-8406-bf9b0e783270.png)

**Comment by rocketfingers** [comment]
Duplikat do zamkniecia
