### ISSUE TITLE
Produkty - dodawanie części

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#27]
Czy można dodać Część z poziomu produkty ? 
Chodzi o to , że gdy przy wpisywaniu nowego produktu , musimy najpierw wpisać części. Czy istnieje taka mozliwość jak przy Kliencie aby dodawać częśc z poziomu Produktu?

![obraz](https://user-images.githubusercontent.com/77233863/108523263-fd644080-72cd-11eb-851d-b716567c4e6a.png)

**Comment by 4YourCompany** [comment]
pojawia się błąd

zamiast sum wartość komponentów, TPZ i Tj są napisy NaN

![obraz](https://user-images.githubusercontent.com/77233863/109416836-d807be80-79c0-11eb-98bc-1b513d969b98.png)

**Comment by PKacprow** [comment]
Tak jak rozmawialiśmy. NaN - oznacza, że dla którejś pozycji brakuje wartości. NIe jest to zmienione na 0 aby przypadkiem nie przekłamywać danych...
