### ISSUE TITLE
Części - dodawanie komponentów

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#28]
Czy można dodawać Komponenty z poziomu części?

Chodzi o to aby przy dopisywaniu nowej części  można było od razu dopisać nowy komponent i go połączyć z częścią?

![obraz](https://user-images.githubusercontent.com/77233863/108523622-6e0b5d00-72ce-11eb-8039-a5e6bddbbcd6.png)

**Comment by PKacprow** [comment]
Dodano opcję w rozwijanej liscie.
