### ISSUE TITLE
Aktywności - logowanie czasu maszyny

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#33]
Czy można dodać logowanie czasu oddzielnie dla maszyny?

![obraz](https://user-images.githubusercontent.com/77233863/108534008-f0e5e500-72d9-11eb-97f8-2f5689b7aaf3.png)

**Comment by rocketfingers** [comment]
Miales Andrzeju napisac czy to ma byc jedna maszyna na step czy jedna maszyna na na wlaczenie odliczania

**Comment by 4YourCompany** [comment]
Jedna maszyna na step do wyboru z listy. Po zakończeniu logowania żeby mozna było wybrać inną maszynę z tej samej listy z tabeli Maszyny
