### ISSUE TITLE
Rodzaje użytkowników

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#35]
Administrator - dostęp do wszystkiego 

Manager - dostęp tylko do jednego rodzaju grupy procesów Produkcja, Oferta, Rozwój

User - tylko dostęp do swojego procesu

**Comment by rocketfingers** [comment]
Andrzeju musisz dużo dokładniej to opisać , bo co to znaczy, ze user widzi tylko swój proces?

**Comment by PKacprow** [comment]
#66

**Comment by rocketfingers** [comment]
w innym tasku
