### ISSUE TITLE
Aktywności - Progres ( procent ukończonia)

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#38]
Czy możemy dodać do aktywności Progres 

Procent ukończenia jako stosunek kroków ukończonych do wszystkich dla danego procesu.

Dla nie rozpoczętych 0%

![obraz](https://user-images.githubusercontent.com/77233863/108632075-5a4a2d00-746d-11eb-976a-e325139b413b.png)

**Comment by rocketfingers** [comment]
Dodana zostanie ilosc kroków do zrobienia
