### ISSUE TITLE
Oferta - Wybierz procesy - dodanie Czas wymagany godzin

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#42]
Poprposzę o dodanie w Ofercie przy wybieraniu procesów Okienka

Czas wymagany godzin

wartości liczbowe od 1 do 10000

![image](https://user-images.githubusercontent.com/77233863/109308475-5a1da900-7842-11eb-8c8a-92c3186455ff.png)

**Comment by PKacprow** [comment]
Różny czas procesu w zaleznosci od oferty
