### ISSUE TITLE
Podwóne potwierdzenie dla USUŃ

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#49]
Czy możemy dodać do każdego USUŃ pytanie

Potwierdź usunięcie!

**Comment by rocketfingers** [comment]
Dodatkowo, kazde usun moze byc wykonane tylko jak niczemu nie jest potrzebne, jesli nie ma klucza obcego(trzeba przejrzeć

.

**Comment by PKacprow** [comment]
Tak jak rozmawialiśmy któregoś razu, prosiłbym o wpisywanie tu miejsc w których to podwójne potwierdzenie należy dodać.
