### ISSUE TITLE
Aktywności - Oferta i Rozwój - brak procesów

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#51]
Po odhaczeniu w Aktywności 

Rozwój
Oferta

nie widać procesów chociaż są przyporządkowane.
Widać wszystkie z produkcji

![image](https://user-images.githubusercontent.com/77233863/109821413-3ee1dd80-7c36-11eb-84b8-3993c8485119.png)

**Comment by rocketfingers** [comment]
Wszystko jest dobrze. O nie widać, bo jako pracownik nie jesteś autoryzowany. Do R też, ale ich nie widać rowniez dlatego, ze oferty są w stanie otwarte.
