### ISSUE TITLE
Aktywnosci - zamykanie stepu 10 tylko po zamknieciu pozostałych

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#53]
Poproszę o to aby nie można było zamknąć stepu 10 bez zakończenia wszystkich pozostałych.

poproszę też o poniższy komunikat.

![image](https://user-images.githubusercontent.com/77233863/110951648-9b837d80-8345-11eb-8e4b-557f0012a99d.png)

**Comment by rocketfingers** [comment]
zrobione
