### ISSUE TITLE
Aktywności - Step 10 automatycznie przesunięcie

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#60]
Czy jest możliwe aby po zamknięciu Stepu 10 w aktywnościach produkt i ilość pojawiały się na magazynie Produkty?
Najpierw przy zamykaniu Stepu 10 pojawiałby się komunikat

![obraz](https://user-images.githubusercontent.com/77233863/113015366-c3644500-917d-11eb-8f4a-95e3c5b0ef2a.png)

Nastepnie na magazynie produkty pojawiałby się produkt 
kontrahent - 4YC
data przyjęcia - według daty zamknięcia stepu 10
w miejscu numer faktury - Produkcja Armatury
Lokacja - brak do uzupełnieni z listy

![obraz](https://user-images.githubusercontent.com/77233863/113015906-438aaa80-917e-11eb-9330-5213e4f50979.png)

**Comment by rocketfingers** [comment]
zrobione
