### ISSUE TITLE
Aktywności - podział na procesy 

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#64]
czy możemy podzielić aktywności według procesów? Chodzi o to żeby były widoczne dla danego użytkownika tak jak dla produkcji Armatury

![obraz](https://user-images.githubusercontent.com/77233863/114311196-07483a00-9aee-11eb-9797-8215bcd26647.png)

**Comment by rocketfingers** [comment]
Andrzeju proszę opisz dokładniej o co tu chodzi?

**Comment by 4YourCompany** [comment]
Chodzi o to, że opis dla pojedyńczego użytkownika który teraz jest aktywności zamienić na opis procesu czyli PRODUKCJA ARMATURY. Dla Admina proszę zostawić Aktywności.

**Comment by rocketfingers** [comment]
Nie powinno sie tak robic
