### ISSUE TITLE
Użytkownicy - rodzaje

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#66]
plik Word

**Comment by rocketfingers** [comment]
[cent.pdf](https://github.com/rocketfingers/YourKpi/files/6332085/cent.pdf)

**Comment by PKacprow** [comment]
[YouKPi - opis.pdf](https://github.com/rocketfingers/YourKpi/files/6417905/YouKPi.-.opis.pdf)
