### ISSUE TITLE
Produkty - rozszerzenie dla ID Produktu

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#67]
Poproszę o możliowść rozszerzenia dla ID Produktu.
Obecnie jest to następujący ciąg znaków

ZK-K_025_063_I_020_120

Poproszę o dodanie możliwości (opcji) dopisania po kropce od dwóch do siedmiu znaków np.

ZK-K_025_063_I_ 020_120.ANSI600

rozszerzenia mogą być następujące

ANSI600
CL150
METAL
L200
L100
H300
WR
BR
PEEK

![obraz](https://user-images.githubusercontent.com/77233863/114936929-6505ba80-9e3d-11eb-92a0-5a6027e78ac6.png)

**Comment by PKacprow** [comment]
@rocketfingers -  może warto się zastanowić, by pod spodem używać innego Id - do tworzenia relacji w bazie?
A to, byłoby dla klienta. Co myślisz?

**Comment by 4YourCompany** [comment]
OK, dobry pomysł. Może po prostu dodać nowe okienko "rozszerzenie"?
