### ISSUE TITLE
Towary - nowe okienka Ceny, Marża,Klient

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#72]
Poproszę o dodanie następujących okienek dla Towary

Cena zakupu - wartość liczbowa wraz z walutą
Cena sprzedaży - wartość liczbowa wraz z walutą
Marża - wartość procentowa Wynik / Cena sprzedaży
Wynik - wynik Cena sprzedaży - Cena zakupu
Klient - wybór z listy Klienci

![obraz](https://user-images.githubusercontent.com/77233863/116929296-83055480-ac5e-11eb-8e4d-50234450ffb3.png)

**Comment by PKacprow** [comment]
Jeśli Towary mają dwie ceny - zakupu i sprzedaży - to którą wyświetlamy w magazynie?
<Na razie ustawiam cenę sprzedaży>
