### ISSUE TITLE
Oferty - wyróżnik dla ofert w realizacji

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#73]
Poproszę o dodanie wyróżnika dla ofert które są w realizacji np. poprzez dodanie koloru zielonego przy dacie zamówienia 

![obraz](https://user-images.githubusercontent.com/77233863/116930235-c90ee800-ac5f-11eb-9d00-74fc41c64f9d.png)

**Comment by PKacprow** [comment]
Rozumiem, że kolumna status nie wystarcza? W takim razie czy kolorem oznaczać tylko datę, czy cały wiersz i czy tylko status 'w trakcie' ma być zaznaczony?

**Comment by 4YourCompany** [comment]
Tu zamykamy więc nowe okienko jest nie potrzebne bo jest status
