### ISSUE TITLE
Klienci - nowe okienko Osoba Kontaktowa

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#74]
Poproszę o dodanie nowego okienka w Klienci - Osoba Kontaktowa

Tu będą wpisywane Imię i Nazwisko

![obraz](https://user-images.githubusercontent.com/77233863/116930851-93b6ca00-ac60-11eb-9f25-d3b3f112bc94.png)

**Comment by PKacprow** [comment]
Czy osoba będzie unikalna dla klienta? Tzn. czy każdy klient będzie miał swoją osobę, czy te osoby to cos w rodzaju przedstawicieli i np. 20 klientów może mieć tę samą osobę?
