### ISSUE TITLE
Oferta - wygląd oferty dodanie logo i tekstu stałego

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#75]
Poproszę o sprawdzenie czy można dodać do wydruku oferty poniższe logo oraz tekst zewnętrzny

![obraz](https://user-images.githubusercontent.com/77233863/117720865-7b562a80-b1df-11eb-884e-0a4347f762d8.png)

![obraz](https://user-images.githubusercontent.com/77233863/117720991-9fb20700-b1df-11eb-8b7b-47eb1713fb66.png)

**Comment by 4YourCompany** [comment]
Oprócz tego poproszę o poprawienie kolumn w wydruku ponieważ zachodzą na siebie i są nieczytelne.

![image](https://user-images.githubusercontent.com/77233863/125600855-8af33df5-d732-4b62-9567-2fd36a69dd9b.png)

**Comment by PKacprow** [comment]
![oferta](https://user-images.githubusercontent.com/12852024/126081199-6150bb93-dc5a-461a-a695-9dd27f51b7f2.png)

**Comment by PKacprow** [comment]
Proponowany wygląd oferty -  do dyskusji oczywiście. Proszę o dołączenie całego tekstu klauzuli....

**Comment by 4YourCompany** [comment]
Ten tekst potrzebuję

Poniższa oferta ma charakter informacyjny i nie stanowi oferty handlowej w rozumieniu art. 66 kodeksu cywilnego. Do oferty załączamy karty katalogowe zaworów. Oferta nie rezerwuje towaru. Oferowane kurki kulowe spełniają wymagania zawarte w normie EN 1983 . Kołnierze wykonane zgodnie z normą EN 1092-1. Kurki wykonane w klasie szczelności „A” (100%) szczelności.  Proponowane przez nas produkty posiadają oznaczenie: CE – na podstawie Certyfikatu Zgodności, wydanego przez UDT, potwierdzającego stosowanie systemu jakości zgodnego z wymaganiami określonymi w module „H” Dyrektywy 2014/68/UE: A - jeżeli podlegają pod wymogi Dyrektywy PED; Do kurków dołączone będzie świadectwo 3.1  zgodnie z EN 10204, które równocześnie stanowi dokument gwarancyjny na okres 60 miesięcy na korpus i kule, na pozostałe części 24 miesiące od daty dostarczenia faktury  i towaru (istnieje możliwość wydłużenia okresu gwarancji).Ceny dotyczą tylko i wyłącznie ilości i wyrobów dla tej konkretnej oferty według numeru, zmiana wyrobów albo ich ilości może skutkować zmianą warunków w tym cen.
