### ISSUE TITLE
Błąd - wszędzie znikneły "stare"ID Produktu

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#82]
Zniknęły "stare ID produktu teraz ich nie ma i są tylko numery.  
Poproszę o przywrócenie starych ID produktu 
Nie widać ich teraz w Aktywnościach , Produkty i Oferta

**Comment by PKacprow** [comment]
Pewnie związane z tą zmianą produktId. W weekend postaram się naprawić.
