### ISSUE TITLE
Błąd - Produkty baza testowa - nie można dodać

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#86]
Nie można dodać nowego produktu po wpisaniu ID w następujący sposób 

![image](https://user-images.githubusercontent.com/77233863/124593548-10cc0e80-de5f-11eb-8624-b081bc04a0d3.png)

wyskakuje taki bład

![image](https://user-images.githubusercontent.com/77233863/124593629-280afc00-de5f-11eb-97a4-56ce508dd21d.png)

a po wpisaniu samego ID o numerze 129 

![image](https://user-images.githubusercontent.com/77233863/124593818-630d2f80-de5f-11eb-895a-fd3a99b20d54.png)

**Comment by rocketfingers** [comment]
Zrobione, proszę przetestuj

**Comment by 4YourCompany** [comment]
Przetestowałem , działa dziękuję
