### ISSUE TITLE
Duplikuj Produkty 

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#9]
Chciałbym móc duplikować Produkty wraz z listami części i komponentów.

Po wciśnieciu DUPLIKUJ żebym mógł dowolnie zmieniać produkt ,i części .

![obraz](https://user-images.githubusercontent.com/77233863/107116307-7dbc8780-6872-11eb-8cf0-0fe03bd5111a.png)

**Comment by PKacprow** [comment]
+ Zabezpieczyć, by częsci duplikatu były inne niż produktu 'oryginalu'
