### ISSUE TITLE
Nowa tabela - Poziomy rabatów

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#92]
poproszę o nową tabelę poziomy rabatów.

![image](https://user-images.githubusercontent.com/77233863/125657710-e278f690-3632-4861-8227-33405a06b988.png)
Ta tabela , żeby była podpięta do Klienta, żebym Klientowi musiał przypisać poziom rabatów
![image](https://user-images.githubusercontent.com/77233863/125658044-667000e9-3440-4618-8825-a550f1960e33.png)
 oraz widoczna przy OFERTA tak , żebym mógł wybierać poziom rabatów i wstawienie ceny po rabacie czyli cena - % rabatu ,

Oprócz tego proszę aby w oknie głównym OFERTA nie były widoczne 

Projekt ID
Typ zamówienia
Liczba procesów

![image](https://user-images.githubusercontent.com/77233863/125658545-cdfeac75-90c6-4871-a846-57043a8f8bb4.png)

**Comment by rocketfingers** [comment]
To jest raczej zly pomysl, bo przeciez rabat nie bedzie zawsze taki sam.

**Comment by 4YourCompany** [comment]
Rabaty poproszę , żeby były widoczne tylko w ofercie . Masz rację zły pomysł
