### ISSUE TITLE
Błąd - nie ma procesów w Księdze Procesów

### ISSUE THREAD

**Issue by 4YourCompany** [rocketfingers/YourKpi#99]
Najpierw mieli przez jakiś czas i jest taki ekran

![image](https://user-images.githubusercontent.com/77233863/129869363-cee7188a-2cf1-4f03-9dcf-aa8b301268d9.png)

a potem wyświetla następujący komunikat

![image](https://user-images.githubusercontent.com/77233863/129869652-0f2a40bf-d88f-464c-a9ca-f6a9f94ccf87.png)

**Comment by rocketfingers** [comment]
kopia #98
